### PR TITLE
fix setTimeout call, fixes #1

### LINKED ISSUE #1: fix setTimeout call
hi,

i'm quite sure that you made a typo in setTimeout call in main.ts.
i'm sending a PR to fix that.

### PR DESCRIPTION
**Pull request by phra**

### CODE REVIEW

**Comment by phra** [comment]
the tests are failing.. interesting..

**Comment by phra** [comment]
What about this @jsynowiec ?

**Comment by jsynowiec** [comment]
Thanks for contribution but I can't merge this. I think that some more information is needed so you can understand why:

1. What you took as a "typo" and wrapped a promise resolver passed to setTimeout in an outer function expression wasn't one. It was intended and by design. It was also working as it should and unit test catched your change.
2. For the sake of adding a shorthand anonymous function expression around the promise resolver (which is unnecessary) you had to rewrite unit tests because you've changed the signature. If this code would have been used by other modules then you've just introduced a breaking change ;)
3. I assume that you've done 1 & 2 to remove the comment suppressing the linter errors, but please read further.
4. As it's stated in the [main.ts#L1](https://github.com/jsynowiec/node-typescript-boilerplate/blob/master/src/main.ts#L1) file, both the missing type annotation for `greeter` function and direct passing of resolver to setTimeout was **one of the purposes of this example and completly indented**. It was to show how to use inline suppression for TSLint.

Side note: also please look at the tests. What you've ended up with is a code duplication in both unit tests while it could be simply written once in `beforeEach` or `beforeAll` for the test suite - if I'm to add another unit test, then I have to repeat the same code third time.

**Comment by phra** [comment]
in your tests the code in main.ts is  bugged (resolve is called immediately without waiting 2000 ms) and tests are bugged too because they don't run the fake timers inside jest. so if for you having a bugged code that doesn't do what you think and tests that don't tests what you are thinking to test is by design.. well, good luck..
of course they "catch" the changes.. they were **BROKEN**! 😒 
and sorry but the excuse of "showing tslint suppression" is not working with me.. there were so many ways to show that, not introducing a bug!
thanks for rejecting this PR that took me time to solve tonight instead of working on something else.. 
and of course keep your **BUGGY BY DESIGN** code and be proud of it. nice bugged starter boilerplate.

**Comment by jsynowiec** [comment]
First, mind your tone. Second, I'm not quite sure what you expect by writing 
> thanks for rejecting this PR that took me time to solve tonight instead of working on something else

I didn't ask you to work on this ¯\_(ツ)_/¯

Third, the purpose of a boilerplate is to deliver configured tooling to start a new project. You're suppose to write your own code :)

What I see is that this example might be confusing. I'm reopening this PR and I'll reconsider merging it but in a different form. Without duplicating the code in tests and while keeping the tslint suppression examples.

**Comment by jsynowiec** [comment]
Closing as it's merged manually after cleanup.

**Comment by phra** [comment]
i will not have the same number of contributions like a PR merged, but np.
thanks anyway. :+1:

**Pull request closed without merging**
